version: 2
jobs:
  build:
    docker:
      - image: node:12-alpine

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

    deploy:
      machine:
        enabled: true
      steps:
        - add-ssh-keys:
            fingerprints:
              - "ad:94:65:40:af:76:e2:28:11:8a:fc:1d:51:b1:8a:f2"
        - run:
            name: Deploy Over SSH
            command: |
              ssh $SSH_USER@$SSH_HOST "cd /c/DarkHorse/University/IT4883/recurrent-task-service && npm install && cd .. && ./shut-down.bat && cd recurrent-task-service && npm run build && npm start"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
