version: 2
jobs:
  build:
    docker:
      - image: node:12-alpine

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b5:46:e9:91:2b:c2:01:0b:0a:b3:47:b5:b2:d0:19:89"
      - run:
          name: Deploy over SSH
          command: |
            ssh -v -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST -p $SSH_PORT "cd $APP_PATH &&
              docker-compose down &&
              git pull origin master &&
              docker container run --rm -v $(pwd):/app node:12-alpine sh -c 'cd /app && npm install' &&
              docker-compose build --force-rm --no-cache &&
              docker-compose up -d"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
